<?php

namespace Omnipay\NMI\Message\ThreeStepRedirect;

class AddSubscriptionToExistingPlanRequest extends AuthRequest
{
    /**
     * @var string
     */
    protected $type = 'add-subscription';

    /**
     * @param $value
     * @return AddSubscriptionToExistingPlanRequest
     */
    public function setStartDate($value)
    {
        return $this->setParameter('start-date', $value);
    }

    /**
     * @return mixed
     */
    public function getStartDate()
    {
        return $this->getParameter('start-date');
    }

    /**
     * @return mixed
     */
    public function getPlanId()
    {
        return $this->getParameter('plan-id');
    }

    /**
     * @param $value
     * @return AddSubscriptionToExistingPlanRequest
     */
    public function setPlanId($value)
    {
        return $this->setParameter('plan-id', $value);
    }

    public function getData()
    {
        $data = parent::getData(); // TODO: Change the autogenerated stub

        $data['start-date'] = $this->getStartDate();
        $data['plan']['plan-id'] = $this->getPlanId();


        unset($data['amount']);
        unset($data['ip-address']);

        return $data;
        //dd($data);
    }
}